CREATE TABLE SALES_STORE(
TRANSACTION_ID VARCHAR(15),
CUSTOMER_ID VARCHAR(15),
CUSTOMER_NAME VARCHAR(30),
CUSTOMER_AGE INT,
GENDER VARCHAR (15),
PRODUCT_ID VARCHAR(15),
PRODUCT_NAME VARCHAR(15),
PRODUCT_CATEGORY VARCHAR(15),
QUANTIY INT,
PRCE FLOAT,
PAYMENT_MODE VARCHAR(15),
PURCHASE_DATE DATE,
TIME_OF_PURCHASE TIME,
STATUS VARCHAR(15)
);

SELECT * FROM SALES_STORE



--DATA CLEANING
SELECT * INTO SALES1 FROM SALES_STORE

--STEP 1:- TO CHECK FOR DUPLICATE
SELECT TRANSACTION_ID, COUNT(*)
FROM SALES1
GROUP BY TRANSACTION_ID
HAVING COUNT(TRANSACTION_ID) > 1

--TXN240646 TXN342128 TXN855235 TXN981773


WITH CTE_DEM AS (
SELECT *,
ROW_NUMBER() OVER (
PARTITION BY TRANSACTION_ID 
ORDER BY TRANSACTION_DATE DESC 
) AS ROW_NUM
FROM SALES1
)

SELECT * FROM CTE_DEM WHERE ROW_NUM = 1; 


--DELETE FROM CTE_DEM
--WHERE ROW_NUM=2

SELECT * FROM CTE_DEM
WHERE TRANSACTION_ID IN('TXN240646', 'TXN342128', 'TXN855235', 'TXN981773')


--STEP 2:-CORRECTION OF HEADERS
SELECT * FROM SALES1

EXEC SP_RENAME 'SALES1.QUANTIY', 'QUANTITY','COLUMN'

EXEC SP_RENAME 'SALES1.PRCE', 'PRICE','COLUMN'


--STEP 3:- TO CHECK DATATYPE
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='SALES1'

--STEP 4:- TO CHECK NULL VALUES

--TO CHECK NULL COUNT
-- To check null count
DECLARE @SQL NVARCHAR(MAX) = '';

SELECT @SQL = STRING_AGG(
'SELECT ''' + COLUMN_NAME + ''' AS ColumnName, 
COUNT(*) AS NullCount 
FROM ' + QUOTENAME(TABLE_SCHEMA) + '.SALES1
WHERE ' + QUOTENAME(COLUMN_NAME) + ' IS NULL',
' UNION ALL '
) WITHIN GROUP (ORDER BY COLUMN_NAME)
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'SALES1';

-- EXECUTE THE DYNAMIC SQL
EXEC sp_executesql @SQL;

--TREATING NULL VALUES

SELECT * FROM SALES1
WHERE TRANSACTION_ID IS NULL
OR
CUSTOMER_ID IS NULL
OR CUSTOMER_NAME IS NULL
OR CUSTOMER_ID IS NULL
OR CUSTOMER_AGE IS NULL
OR GENDER IS NULL
OR PRODUCT_ID IS NULL
OR PRODUCT_NAME IS NULL
OR PRODUCT_CATEGORY IS NULL
OR QUANTITY IS NULL
OR PAYMENT_MODE IS NULL
OR PURCHASE_DATE IS NULL
OR TIME_OF_PURCHASE IS NULL
OR STATUS IS NULL

DELETE FROM SALES1
WHERE TRANSACTION_ID IS NULL

SELECT * FROM SALES1
WHERE CUSTOMER_NAME='EHSAAN RAM'


UPDATE SALES1
SET CUSTOMER_ID='CUST9494'
WHERE TRANSACTION_ID='TXN977900'

SELECT * FROM SALES1
WHERE CUSTOMER_NAME='DAMINI RAJU'

UPDATE SALES1
SET CUSTOMER_ID='CUST1401'
WHERE TRANSACTION_ID='TXN977900'

SELECT * FROM SALES1
WHERE CUSTOMER_ID='CUST1003'

UPDATE SALES1
SET CUSTOMER_NAME='CUST1401', CUSTOMER_AGE=35, GENDER='MALE'
WHERE TRANSACTION_ID='TXN432798'

SELECT  * FROM SALES1
 

--STEP 5:- DATA CLEANING

SELECT DISTINCT GENDER
 FROM SALES1
UPDATE SALES
SET GENDER='M'
WHERE GENDER='MALE'

SELECT DISTINCT GENDER
FROM SALES1
UPDATE SALES
SET GENDER='F'
WHERE GENDER='FEMALE'

--CLEANING PAYMENT COLUMN

SELECT DISTINCT PAYMENT_MODE
FROM SALES1

UPDATE SALES1
SET PAYMENT_MODE='CREDIT CARD'
WHERE PAYMENT_MODE='CC'

 --DATA ANALYSIS--

 --TOP 5 MOST SELLING PRODUCTS BY QUANTITY--

SELECT * FROM SALES1
SELECT DISTINCT STATUS
FROM SALES1

SELECT TOP 5 PRODUCT_NAME, SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM SALES1
WHERE STATUS='DELIVERED'
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_QUANTITY_SOLD DESC;

--BUSINESS PROBLEM: WQE DON'T KNOW WHICH PRODUCTS ARE MOST IN DEMAND.

--BUSINESS IMPACT: HELPS PRIORITIZE STOCK AND BOOST SALES THROUGH TARGETED PROMOTIONS.

-----------------------------------------------------------------------------------

--2. MOST FREQUENTLY CANCELED PRODUCT


SELECT TOP 5 PRODUCT_NAME, COUNT(*) AS TOTAL_CANCELLED
FROM SALES1
WHERE STATUS='CANCELLED'
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_CANCELLED DESC;

--BUSINESS PROBLEM: FREQUENT CANCELLATIONS AFFECT REVENUE AND DCUATOMER TRUST.

--BUSINESS IMPACT: IDENTIFY POOR PERFORMING PRODUCTS TO IMPROVE QUALITY OR REMOVE FROM CATALOG.

------------------------------------------------------------------------------------------

--3. WHAT TIME OF THE DAY HAS THE HIGHEST NUMBER OF PURCHASE?

SELECT * FROM SALES1

SELECT
CASE
WHEN DATEPART(HOUR, TIME_OF_PURCHASE) BETWEEN 0 AND 5 THEN 'NIGHT'
WHEN DATEPART(HOUR, TIME_OF_PURCHASE) BETWEEN 6 AND 11 THEN 'MORNING'
WHEN DATEPART(HOUR, TIME_OF_PURCHASE) BETWEEN 12 AND 17 THEN'AFTERNOON'
WHEN DATEPART(HOUR, TIME_OF_PURCHASE) BETWEEN 18 AND 23 THEN 'EVENING'
END AS TIME_OF_DAY,
COUNT(*) AS TOTAL_ORDERs
FROM SALES1
GROUP BY
CASE
WHEN DATEPART(HOUR, TIME_OF_PURCHASE) BETWEEN 0 AND 5 THEN 'NIGHT'
WHEN DATEPART(HOUR, TIME_OF_PURCHASE) BETWEEN 6 AND 11 THEN 'MORNING'
WHEN DATEPART(HOUR, TIME_OF_PURCHASE) BETWEEN 12 AND 17 THEN'AFTERNOON'
WHEN DATEPART(HOUR, TIME_OF_PURCHASE) BETWEEN 18 AND 23 THEN 'EVENING'
END
ORDER BY TOTAL_ORDERS DESC

--BUSINESS PROBLEM SOLVED: FIND PEAK SALES TIMES.

--BUSINESS IMPACT: OPTIMIZE STAFFING, PROMOTIONS AND SERVER LOADS.
------------------------------------------------------------------------------------------

--4. TOP 5 HIGHEST SPENDING CUSTOMERS.

SELECT * FROM SALES1

SELECT TOP 5 CUSTOMER_NAME, 
FORMAT(SUM(PRICE*QUANTITY),'CO', 'EN-IN') AS TOTAL_SPEND
FROM SALES
GROUP BY CUSTOMER_NAME
ORDER BY SUM(PRICE*QUANTITY) DESC

--BUSINESS PROBLEM SOLVED: IDENTIFY VIP CUSTOMERS.

--BUSINESS IMPACT: PERSONALIZED OFFERS, LOYALTY REWARDS AND RETENTION.
------------------------------------------------------------------------------------------

--5. HIGHES REVENUE PRODUCT CATEGORY.

SELECT * FROM SALES1

SELECT
PRODUCT_CATEGORY,
FORMAT(SUM(PRICE*QUANTITY),'CO', 'en-IN') AS REVENUE 
FROM SALES1
GROUP BY PRODUCT_CATEGORY
ORDER BY SUM(PRICE*QUANTITY) DESC

--BUSINESS PROBLEM SOLVED: IDENTIFY TOP-PERFORMING PRODUCT CATEGORIES.

--BUSINESS IMPACT: EFINE PRODUCT STRATEGY, SUPPLY CHAIN, AND PROMOTONS.
--ALLOWING THE BUSINESS TO INVEST MORE IN HIGH-MARGIN OR HIGH-DEMAND CATEGORIES.

------------------------------------------------------------------------------------------

--6. RETUN/CANCELLATION RATE PER PRODUCT CATEGORY.

SELECT * FROM SALES1

--CANCELLATION

SELECT PRODUCT_CATEGORY,
FORMAT(COUNT(CASE WHEN STATUS='CANCELED' THEN 1 END)"100.0/COUNT("), 'N3')+ ' %' AS CANCELLED_PERCENTAGE
FROM SALES1
GROUP BY PRODUCT_CATEGORY
ORDER BY CANCELLED_PERCENT DESC

--RETURN
SELECT PRODUCT_CATEGORY,
FORMAT(COUNT(CASE WHEN STATUS='RETURNED' THEN 1 END)"100.0/COUNT("), 'N3')+ ' %' AS RETURNED_PERCENTAGE 
FROM SALES1


--BUSINESS PROBLEM SOLVED: MONITOR DISSATISFACTION TRENDS PER CATEGORY.

--BUSINESS IMPACT: REDUCE RETURNS, IMPROVE PRODUCT DESCRIPTION/EXPECTATIONS.
--HELPS INDETIFY AND FIX PRODUCT OR LOGISTICS ISSUES

-------------------------------------------------------------------------------------

--7. MOST PREFERRED PAYMMENT MODE

SELECT * FROM SALES1
SELECT PAYMENT_MODE, COUNT(PAYMENT_MODE) AS TOTAL_COUNT
FROM SALES
GROUP BY PAYMENT_MODE
ORDER BY TOTAL_COUNT DESC

--BUSINESS PROBLEM SOLVED: KNOW WHICH PAYMENT OPTIONS CUSTOMER PREFER.
--BUSINESS IMPACT: STREAMLINE PAYMENT PROCESSING, PRIORITIZE POPULAR MODES

-------------------------------------------------------------------------------------

--8. HOW DOES AGE GROUP AFFECT PURCHASING BEHAVIOUR?

SELECT 
CASE
WHEN CUSTOMER_AGE BETWEEN 18 AND 25 THEN '8-25'
WHEN CUSTOMER_AGE BETWEEN 26 AND 35 THEN '26-35'
WHEN CUSTOMER_AGE BETWEEN 36 AND 50 THEN '36-50'
ELSE '51+'
END AS CUSTOMER_AGE,
FORMAT(SUM(PRICE*QUANTITY),'CO', 'EN-IN') AS TOTAL_PURCHASE
FROM SALES1
GROUP BY CASE
WHEN CUSTOMER_AGE BETWEEN 18 AND 25 THEN '8-25'
WHEN CUSTOMER_AGE BETWEEN 26 AND 35 THEN '26-35'
WHEN CUSTOMER_AGE BETWEEN 36 AND 50 THEN '36-50'
ELSE '51+'
END
ORDER BY SUM(PRICE*QUANTITY) DESC

--BUSINESS PROBLEM SOLVED: UNDERSTAND CUSTOMER DEMOGRAPHICS.
--BUSINESS IMPACT: TARGETED MARKETING AND PRODUCT RECOMMENDATIONS BY AGE GROUP.

-------------------------------------------------------------------------------------

--9. WHAT'S THE MONTHLY SALES TREND?
SELECT * FROM SALES1
--METHOD 1

SELECT
FORMAT(PURCHASE_DATE, 'YYYY-MM') AS MONTH_YEAR,
FORMAT(SUM(PRICE*QUANTITY), CO, 'en-IN') AS TOTAL_SALES,
SUM(QUANTITY) AS TOTAL_QUANTITY
FROM SALES1
GROUP BY FORMAT(PURCHASE_DATE, 'YYYY-MM');

--method 2

SELECT 
YEAR(PURCHASE_DATE)AS YEARS,
MONTH(PURCHASE_DATE) AS MONTHS,
FORMAT(SUM(PRICE*QUANTITY), CO, 'en-IN' AS TOTAL_SALES,
SUM(QUANTITY) AS TOTAL_QUANTITY
FROM SALES1
GROUP BY YEAR(PURCHASE_DATE),
MONTH(PURCHASE_DATE)
ORDER BY MONTHS

--SELECT (4628608+339442)

--BUSINESS PROBLEM: SALES FLUCTUATIONS GO UNNOTICED.
--BUSINESS IMPACT: PLAN INENTORY AND MARKETING ACCORDING TO SEASONAL TRENDS.



--10. ARE CERTAIN GENDERS BUYING MORE SPECIFIC PRODUCT CATEGORIES?

SELECT * FROM SALES1;

--METHOD 1

SELECT GENDER, PRODUCT_CATEGORY, COUNT(PRODUCT_CATEGORY) AS TOTAL_PURCHASE
FROM SALES1
GROUP BY GENDER, PRODUCT_CATEGORY
ORDER BY GENDER

--METHOD 2

SELECT GENDER.PRODUCT_CATEGORY
FROM SALES1
AS SOURCE_TABLE
PIVOT(
COUNT(GENDER)
FOR GENDER IN ([MALE], [FEMALE])
)
AS PIVOT_TABLE
ORDER BY PRODUCT_CATEGORY

--BUSINESS PROBLEM SOLVED: GENDER-BASED PRODUCT PREFERENCES.
--BUSINESS IMPACT: PERSONALIZED ADS, GENDER-FOCUSED CAMPAIGNS.

----------------------------------------------------------------------------------